"use client";

import { useState } from "react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

const MAX_LENGTH = 30;
const MIN_LENGTH = 10;

/**
 * Opmerking input - hard maxLength (30), live "x/30" counter, and a
 * visual "too short" indicator once the field has been touched and is
 * still under 10 chars (server requires 10-30 chars for every
 * movementType except "transfer_intern"). For "transfer_intern" the
 * field is not editable - the opmerking is auto-generated server-side -
 * so this renders a read-only note instead.
 */
export function RemarkInput({
  value,
  onChange,
  autoGenerated = false,
}: {
  value: string;
  onChange: (value: string) => void;
  autoGenerated?: boolean;
}) {
  const [touched, setTouched] = useState(false);

  if (autoGenerated) {
    return (
      <div className="flex flex-col gap-1 text-sm font-medium text-foreground">
        Opmerking
        <p className="text-sm text-muted-foreground">
          Opmerking wordt automatisch ingevuld
        </p>
      </div>
    );
  }

  const length = value.length;
  const tooShort = touched && length < MIN_LENGTH;

  return (
    <label className="flex flex-col gap-1 text-sm font-medium text-foreground">
      Opmerking
      <Input
        type="text"
        value={value}
        maxLength={MAX_LENGTH}
        onChange={(e) => onChange(e.target.value)}
        onBlur={() => setTouched(true)}
        aria-label="Opmerking"
        aria-invalid={tooShort}
        className="h-14 rounded-xl text-base"
      />
      <span className={cn("text-xs text-muted-foreground", tooShort && "text-destructive")}>
        {length}/{MAX_LENGTH}
        {tooShort && ` - minstens ${MIN_LENGTH} karakters`}
      </span>
    </label>
  );
}
