"use client";

import { PackageOpen, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScannerInput } from "../../shared/scanner-input";
import { useStockBeweging } from "../hooks/use-stock-beweging";
import { MovementTypeSelector } from "./movement-type-selector";
import { QuantityInput } from "./quantity-input";
import { RemarkInput } from "./remark-input";
import { MagazijnInput } from "./magazijn-input";
import { StockbewegingConfirmDialog } from "./stockbeweging-confirm-dialog";
import { StockbewegingResultState } from "./stockbeweging-result-state";
import { StockbewegingErrorState } from "./stockbeweging-error-state";

const MIN_OPM_LENGTH = 10;
const MAX_OPM_LENGTH = 30;

/**
 * Top-level container for the NPP "Stockbeweging boeken" tile. Owns no
 * state itself - the step machine (artikel -> form -> confirm -> result)
 * lives in useStockBeweging. Confirmation is mandatory: the only way to
 * reach postStockBeweging is through StockbewegingConfirmDialog's
 * "Bevestigen" button.
 */
export function StockbewegingView() {
  const sb = useStockBeweging();
  const { step, scanResult, scanLoading, scanError, article, result } = sb;

  const isTransferIntern = sb.movementType === "transfer_intern";
  const aantalValid = isTransferIntern || (sb.aantal.trim() !== "" && Number(sb.aantal) > 0);
  const opmValid =
    isTransferIntern ||
    (sb.opm.trim().length >= MIN_OPM_LENGTH && sb.opm.trim().length <= MAX_OPM_LENGTH);
  const magazijnValid = !isTransferIntern || sb.nieuwMagazijn.trim().length > 0;
  const isFormValid = sb.movementType !== null && aantalValid && opmValid && magazijnValid;

  return (
    <div className="flex h-full w-full flex-col gap-6 p-6 sm:p-8">
      <div>
        <h1 className="font-heading text-xl font-semibold text-foreground">
          Stockbeweging boeken
        </h1>
        <p className="text-sm text-muted-foreground">
          Scan een artikel en boek een stockbeweging
        </p>
      </div>

      {step === "artikel" && (
        <>
          <ScannerInput
            onSubmit={sb.submitScan}
            loading={scanLoading}
            placeholder="Scan artikel..."
            ariaLabel="Artikel scannen"
          />

          {scanError && <StockbewegingErrorState message={scanError} />}

          {scanResult?.status === "not_found" && (
            <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-border bg-card p-8 text-center">
              <PackageOpen className="size-10 text-muted-foreground" strokeWidth={1.75} />
              <p className="text-base font-medium text-foreground">Artikel niet gevonden</p>
              <p className="text-sm text-muted-foreground">
                Geen artikel gevonden voor scan &quot;{scanResult.scan}&quot;.
              </p>
            </div>
          )}

          {scanResult?.status === "multiple" && (
            <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-border bg-card p-8 text-center">
              <AlertTriangle className="size-10 text-muted-foreground" strokeWidth={1.75} />
              <p className="text-base font-medium text-foreground">Meerdere artikelen gevonden</p>
              <p className="text-sm text-muted-foreground">
                Meerdere artikelen gevonden voor deze scan. Neem contact op met de administratie.
              </p>
            </div>
          )}
        </>
      )}

      {(step === "form" || step === "confirm") && article && (
        <>
          <div className="rounded-2xl border border-border bg-card p-4">
            <h2 className="text-lg font-semibold text-foreground">{article.artnr}</h2>
            <p className="text-sm text-muted-foreground">{article.omschrijving}</p>
          </div>

          <MovementTypeSelector value={sb.movementType} onChange={sb.setMovementType} />

          {sb.movementType && !isTransferIntern && (
            <QuantityInput value={sb.aantal} onChange={sb.setAantal} />
          )}

          {sb.movementType && (
            <RemarkInput
              value={sb.opm}
              onChange={sb.setOpm}
              autoGenerated={isTransferIntern}
            />
          )}

          {sb.movementType && isTransferIntern && (
            <MagazijnInput value={sb.nieuwMagazijn} onChange={sb.setNieuwMagazijn} />
          )}

          {step === "form" && (
            <Button
              type="button"
              onClick={sb.goToConfirm}
              disabled={!isFormValid}
              className="h-14 rounded-xl px-6 text-base"
            >
              Doorgaan
            </Button>
          )}

          <StockbewegingConfirmDialog
            open={step === "confirm"}
            article={article}
            movementType={sb.movementType ?? "correctie_plus"}
            aantal={sb.aantal}
            opm={sb.opm}
            nieuwMagazijn={sb.nieuwMagazijn}
            submitting={sb.submitting}
            error={sb.submitError}
            onConfirm={sb.confirmBooking}
            onCancel={sb.goBackToForm}
          />
        </>
      )}

      {step === "result" && result && (
        <StockbewegingResultState result={result} onReset={sb.reset} />
      )}
    </div>
  );
}
