import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { RemarkInput } from "../remark-input";

describe("RemarkInput", () => {
  it("enforces a hard maxLength of 30 and shows a live counter", () => {
    render(<RemarkInput value="Correctie na telling" onChange={() => {}} />);
    const input = screen.getByLabelText("Opmerking");
    expect(input).toHaveAttribute("maxlength", "30");
    expect(screen.getByText("20/30")).toBeInTheDocument();
  });

  it("shows a too-short indicator only once the field is touched and under 10 chars", async () => {
    const user = userEvent.setup();
    render(<RemarkInput value="kort" onChange={() => {}} />);
    const input = screen.getByLabelText("Opmerking");

    expect(input).toHaveAttribute("aria-invalid", "false");

    await user.click(input);
    await user.tab();

    expect(input).toHaveAttribute("aria-invalid", "true");
    expect(screen.getByText(/minstens 10 karakters/)).toBeInTheDocument();
  });

  it("does not show the too-short indicator once >= 10 chars", async () => {
    const user = userEvent.setup();
    render(<RemarkInput value="Lang genoeg opmerking" onChange={() => {}} />);
    const input = screen.getByLabelText("Opmerking");

    await user.click(input);
    await user.tab();

    expect(input).toHaveAttribute("aria-invalid", "false");
  });

  it("renders a read-only auto-generated note instead of an editable field when autoGenerated", () => {
    render(<RemarkInput value="" onChange={() => {}} autoGenerated />);
    expect(screen.getByText("Opmerking wordt automatisch ingevuld")).toBeInTheDocument();
    expect(screen.queryByLabelText("Opmerking")).not.toBeInTheDocument();
  });

  it("calls onChange as the user types", async () => {
    const user = userEvent.setup();
    const onChange = vi.fn();
    render(<RemarkInput value="" onChange={onChange} />);

    await user.type(screen.getByLabelText("Opmerking"), "x");
    expect(onChange).toHaveBeenCalledWith("x");
  });
});
